# Generated by Django 5.0.6 on 2024-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincolor_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='body_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
